apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        ports:
        - containerPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
  - port: 3200
    targetPort: 3200
  selector:
    app: tempo
