apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - name: golang-api
        image: golang-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: golang-api
